### ISSUE TITLE
Mention preferred package name in READ.md

### ISSUE THREAD

**Issue by alwinvandeput** [SAP/code-pal-for-abap-cloud#51]
My proposal is to mention a preferred package name for the code.
I now used the package name /CC4A/MAIN.

**Comment by bjoern-jueliger-sap** [comment]
What benefit would such a preferred name have? Personally I use `/CC4A/CODE_PAL` but what difference does that make to your `/CC4A/MAIN` or whatever anyone else might pick?

**Comment by alwinvandeput** [comment]
I think it helps people to choose a package name. 
It is also helps for consistency reasons so that on every system the package name is the same. 
And it helps that people choose an name starting with /CC4A/ and not with Z or Y.

**Comment by mbtools** [comment]
Agree. Of course, abapGit lets you pick any package, but it's nice if a project has a consistent home.

I use "Recommended SAP package: ..." in my READMEs. [Example](https://github.com/Marc-Bernard-Tools/ABAP-Tools-for-abapGit?tab=readme-ov-file#installation)
