### ISSUE TITLE
Pull errors

### ISSUE THREAD

**Issue by nav-the** [SAP/code-pal-for-abap-cloud#62]
I'm trying to pull the git repository in the BTP ABAP cloud but the pull ended up in errors.  The object log shows the below error.
/CC4A/RFC_ENABLED_MODULE_RFC | SCO2 | E | Function module /CC4A/RFC_ENABLED_MODULE does not exist
/CC4A/RFC_ENABLED_MODULE_RFC | SCO2 | E | Import of object /CC4A/RFC_ENABLED_MODULE_RFC failed

Any advise would be appreciated to clear up this error.  
Thanks

**Comment by bjoern-jueliger-sap** [comment]
This is probably an inconsistency in the abapGit importer for SCO2 objects. The SCO2 object is in the end not relevant for the actual execution of the CodePal anyway. If you just activate all imported objects anyway, does it work? (Try executing an ATC check with check variant /CC4A/CODE_PAL_FULL on any object)

**Comment by nav-the** [comment]
Thanks.  As suggested, activated all the imported objects and its success.  Executed ATC check on a object available in BTP abap environment and it worked.  
But I see the check variant /CC4A/CODE_PAL_FULL is not remote enabled.  So unable to run the remote ATC scenario with on-prem ABAP objects.  Is this something related to inconsistency during git pull?

**Comment by bjoern-jueliger-sap** [comment]
Ah, that's because the "Prefer Methods" check is not currently remote-enabled (we cannot tell whether a function module is an RFC module with the currently released APIs). If you copy the variant and remove the "Prefer Methods" check the resulting variant should be remote-enabled.

**Comment by nav-the** [comment]
Thanks.  Removed the "Prefer Methods" check and it worked.
