### ISSUE TITLE
Quick fix proposal description issue for Remote ATC scenario

### ISSUE THREAD

**Issue by nav-the** [SAP/code-pal-for-abap-cloud#63]
Installed Code Pal on BTP ABAP and use that to do the clean code checks for remote on-prem S/4 systems.  The remote checks are working fine.  When tried quick fix, the proposal doesn't show the description.  It displays 'The Quick fix does not have a description'.  But the local checks in BTP ABAP show the quick fix proposal description.  The quick fix is working and its just the proposal description missing in remote scenario.  Is that something that can be sorted?

**Comment by bjoern-jueliger-sap** [comment]
This is not a problem with Code Pal itself, but with SAP's ATC infrastructure. Please install note [3406781](https://launchpad.support.sap.com/#/notes/3406781) to fix it

**Comment by nav-the** [comment]
The note is still not released but will check when available.  Thanks..
